global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX метрики
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka-jmx-exporter:9404']
    scrape_interval: 10s
    metrics_path: /metrics

  # Spring Boot приложение (если добавите actuator)
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s